### ISSUE TITLE
[error: invalidAccess] when adding as package dependency 

### ISSUE THREAD

**Issue by AlexPinhasov** [jpsim/Yams#275] opened 2020-09-07 17:12 UTC
I added the package as a dependency
Building the first time I get "error: invalidAccess" from Xcode

<img width="350" alt="Screen Shot 2020-09-07 at 20 10 02" src="https://user-images.githubusercontent.com/26197528/92408457-322c7300-f146-11ea-8984-6a1ab5cd160f.png">

Any idea why?

**Comment by jpsim** [comment] 2020-09-08 13:47
I'm not familiar with that error. Can you share steps to reproduce it? Xcode version, step-by-step instructions?

If this is an Xcode bug, you might want to [report a bug with Apple](https://developer.apple.com/bug-reporting).

**Comment by AlexPinhasov** [comment] 2020-09-08 13:53
I have a swift package I created and added a dependency to your package
![Screen Shot 2020-09-08 at 16 50 42](https://user-images.githubusercontent.com/26197528/92485320-7295fa80-f1f3-11ea-938d-59ddf9dcc96d.png)

After that I created a release in GitHub and added my package as a dependency in my Xcode project, building the first time I get this error, building the second time I see
![Screen Shot 2020-09-08 at 16 52 10](https://user-images.githubusercontent.com/26197528/92485477-a7a24d00-f1f3-11ea-8f52-e4c8e07c480e.png)

Do you think that's an Xcode bug? or SPM bug?

*Note before adding a dependency to your package I didn't have this issue

**Comment by jpsim** [comment] 2020-09-08 15:47
It looks like Yams is being built in a custom shell script named "Auto Localized" and not by Xcode directly. Could that be related to the problem you're seeing?

> Do you think that's an Xcode bug? or SPM bug?

Unless you can reproduce the issue in a Swift Package Manager example using just the command line, it's unlikely that reporting a bug at bugs.swift.org would be looked at, since you're seeing this issue with Xcode's integration of SwiftPM.

> *Note before adding a dependency to your package I didn't have this issue

That makes sense given that the error you're seeing has to do with resolving Yams.

**Comment by AlexPinhasov** [comment] 2020-09-08 16:12
So the "shell script named "Auto Localized" is my shell script that triggers the build/release of my executable package.
I am using "swift release -c" to build and publish my executable for execution.

<img width="1247" alt="Screen Shot 2020-09-08 at 19 10 59" src="https://user-images.githubusercontent.com/26197528/92501303-08875080-f207-11ea-96db-ea4c9b3a24af.png">

that's the code I use to build.
what does "Resolving" means after cloning YAMS?

**Comment by jpsim** [comment] 2020-09-08 21:54
By the way, the `.invalidAccess` error is defined in Swift Package Manager [here](https://github.com/apple/swift-package-manager/blob/605d50e4d934e52d2aaaf15b7f37fc1ab77e9fb7/swift-tools-support-core/Sources/TSCBasic/FileSystem.swift#L15-L21).

> Access to the path is denied.
>
> This is used when an operation cannot be completed because a component of
> the path cannot be accessed.
>
> Used in situations that correspond to the POSIX EACCES error code.

So it looks like it may have been a transient file I/O error.

---

"Resolving" is the word that the Swift Package Manager uses to find out what version of a dependency to use.

**Comment by AlexPinhasov** [comment] 2020-09-09 08:49
The funny thing is that if I try and build again it works fine, I have a CI platform that fails every time because the first build fails. I am out of ideas, but I guess that's not your problem.
Trying to think whats different the second build from the first

**Comment by jpsim** [comment] 2020-09-09 15:31
Is this failing CI job publicly accessible? If it fails reliably, I could help you reduce the repro steps and help report the issue at bugs.swift.org.

**Comment by AlexPinhasov** [comment] 2020-09-10 11:19
It fails exactly like Xcode since it fails in xcodebuild step for archive, I noticed in Swiftlint they use "MakeFile" to link the framework and their executable, maybe that's a better approach?
Not really sure where to begin

**Comment by AlexPinhasov** [comment] 2020-09-17 08:42
Interesting thing I found, if the same package added manually via dragging it to project it works fine, looks like it's only when using SPM to add a dependency

**Closed** 2020-09-25 17:00 UTC
